### ISSUE TITLE
About positive definite matrix in variables?

### ISSUE THREAD

**Issue by Xiaolin-Song** [jump-dev/Convex.jl#226]
In Convex package , it has "x= Semidefinite( )"  to set the variables be a   symmetric semidefinite matrix,
Does it  possible to set the matrix  symmetric be strictly positive definite.

**Comment by hurak** [comment]
I am also curious how to do that. 

Rather then introducing a new constructor for positive definite matrices, I reckon that this could be done in two steps (and it is done like that in some other packages, say in CVX for Matlab):

1) Define a symmetric matrix X or size n x n: in Julia I would expect something like 
`X = Variable(2,2,Symmetric())`
or possibly
`X = Symmetric(n)` 

2) Introduce the constraint 
`X >= eye(n,n)`

Classical motivation comes from control theory and (linear) dynamical system where one needs to check if the following admits a solution:

A' X + X A < 0
X >0

which can be rewritten using nonstrict inequalities as 

A' X + X A <= -epsilon
X >= epsilon

which can be scaled without loss of generality (thanks to homogeneity of LMIs) to 

A' X + X A <= -I
X >= I

I do not know how to implement this test in Convex.jl.

**Comment by odow** [comment]
I'm now aware of a solver with support for strict positive definite matrices. In addition, all solvers use tolerances for computation, so even checks for positive semidefinite allow some wiggle room (e.g., smallest eigen value of `-1e-4`). You'd probably have to do something like @hurak suggests, but you might encounter numerical problems.

Closing because there doesn't seem to be anything actionable here. 

For future readers, modeling questions like this are better asked on the community forum: https://discourse.julialang.org/c/domain/opt/13
