### ISSUE TITLE
sparse variables

### ISSUE THREAD

**Issue by chiumichael** [jump-dev/Convex.jl#285]
Is there a way to declare that a variable is sparse? One of my constraints is a sparse matrix and it seems like not being able to declare that the variable (essentially b in Ax = b, where A is sparse) is killing my memory. Or maybe it doesn't matter. Would appreciate any insight into the matter, thanks!

**Comment by ericphanson** [comment]
I'm not sure I can be of any help, but what I can mention is that the way Convex works now is that it transforms your problem to the (primal) standard conic form of MathProgBase (https://mathprogbasejl.readthedocs.io/en/latest/conic.html). So the main things that get passed to the solver are a matrix of constraints `A`, a constant vector `b`, and a vector corresponding to the objective function `c`. You can actually see what these are by `Convex.conic_problem`, and they are all stored as sparse objects:
```julia
julia> c, A, b, cones, var_to_ranges, vartypes, conic_constraints = Convex.conic_problem(prob);
julia> typeof(A)
SparseArrays.SparseMatrixCSC{Float64,Int64}

julia> typeof(c)
SparseArrays.SparseMatrixCSC{Float64,Int64}

julia> typeof(b)
SparseArrays.SparseMatrixCSC{Float64,Int64}
```

However, I don't have a good handle on the whole pipeline to get there, and there could be memory-eating dense objects along the way. Apparently even the sparse objects can cause problems also (mentioned here: https://github.com/JuliaOpt/Convex.jl/pull/258).

**Comment by chiumichael** [comment]
Thanks for the reply, it does help somewhat, at least I know now that it's not something with a quick fix / work around

**Comment by ericphanson** [comment]
Sure, if you post a minimal example that shows the memory issues, that would be helpful-- I wonder if it's from the same cause as https://github.com/JuliaOpt/Convex.jl/issues/254 or if it's something different.

But re-reading your post, I see it's the variables that you want to be sparse. I think you would need some kind of specialized solver to handle that-- I think most solvers use dense representations of the vectors of variables, and I think most algorithms would require dense representations. I'm not an expert on optimization though.

If you want to see if it's really Convex.jl or the solver, one thing you can do is step through `solve!` by hand. The main job of Convex is the following line, which converts the problem as you've formulated it into the standard form:
```julia
c, A, b, cones, var_to_ranges, vartypes, conic_constraints = Convex.conic_problem(problem)
```
At this point, if you're already having memory problems, then it's in Convex's formulation of the problem, which should not involve allocating any memory for the variables. That is to say, the problem is with how Convex assembles the objective function and constraints into the standard form, but not the particular allocation of the variables. Continuing on,
```julia
problem.model = MathProgBase.ConicModel(solver)

# load MPB conic problem
m = problem.model
load_problem!(m, c, A, b, cones, vartypes)
```
This uses MathProgBase to send the problem to the solver; if the memory issues are here but not earlier then I think it is an issue with MathProgBase or the solver. Then we can actually try to solve the problem
```julia
# optimize MPB conic problem
MathProgBase.optimize!(m)
```
(so if there is a problem here it is likely the solver or possibly MathProgBase) and lastly we need to retrieve the results so you can access them with e.g. `evaluate`:
```julia
populate_solution!(m, problem, var_to_ranges, conic_constraints)
```
Here I believe Convex does allocate vectors to hold the solutions, so there could be a memory problem here. And now we've essentially stepped through all of `solve!`.

It would be nice to figure out what causes high memory usage, so let me know if you find anything.

**Comment by odow** [comment]
Closing as stale, and probably as a duplicate of #254.
