### ISSUE TITLE
`sumsmallest`/`sumlargest` behavior for k=0

### ISSUE THREAD

**Issue by rbalexan** [jump-dev/Convex.jl#423]
I ran into this when writing a program for robust optimization, which involves robustness with respect to removing the k-largest elements. I wanted to check that the result of solving the original non-robust formulation was equivalent to the result of solving the robust reformulation (with k=0), but when solving the program with constraints of the form:
```... + sumlargest(A, k) + ...```

I ran into this error:
```sumlargest and sumsmallest only support positive values of k```

Is there any reason that `sumlargest` and `sumsmallest` can't behave as 0 for k=0? There is some simplicity and convenience in this kind of behavior... 🙂

**Comment by ericphanson** [comment]
Sounds reasonable, seems basically like
```julia
julia> sum(Number[])
0
```
Note that
```julia
julia> sum([])
ERROR: MethodError: no method matching zero(::Type{Any})
```
errors, I think basically because it doesn't know what kind of result to return, but I think we are more like the `Number[]` case, where we know the result should be a number even if we don't know what type, so it returns the integer 0. In #429 I use `Constant(0)` which I think is analogous.

Should be added in Convex 0.14.5 in an hour or so then.
