### ISSUE TITLE
Suppress warning messages from Mosek

### ISSUE THREAD

**Issue by JinraeKim** [jump-dev/Convex.jl#424]
Before beginning, thanks to you all who create and maintain this great package :)

# Questions
I’ve found that `solve!` with `silent_solver=true` or `LOG=false` cannot prevent other warning messages from MOSEK such as MOSEK warning 705: #1 (nearly) zero elements are specified in sparse row ''(11) of matrix 'A'.

Is there any way to make them not to provide warning messages?

For the reproduction of error, I'm sorry but it's hard for me to make a similar situation.

# Notes
- [The original post](https://discourse.julialang.org/t/how-to-set-verbose-false-for-mosek-in-convex-jl/46378/5?u=ihany) in Julia Discourse.

**Comment by ericphanson** [comment]
I'm not sure; these messages are being printed by MOSEK, not by Convex.jl or other Julia code, so maybe there is some other setting you can pass to ask them to not print the messages. Since MOSEK is a commercial product I would ask their support team.

However there are some workarounds you can try: the packages https://github.com/JuliaDocs/IOCapture.jl or https://github.com/JuliaIO/Suppressor.jl provide ways to suppress or store outputs into variables instead of printing them. And on Julia 1.6 you can try
```julia
redirect_stdout(devnull) do
    println("one")
    ...other code
end # nothing shows up
```
I think these should work to suppress the output from MOSEK, but I'm not totally sure (and I don't have a license so I can't try myself).

**Comment by JinraeKim** [comment]
Thanks a lot :) I will try it.

**Comment by ericphanson** [comment]
I'll close this issue because I don't think there's anything we can do in Convex.jl for this.
