### ISSUE TITLE
Problem Depot test in lp_dual_abs_atom

### ISSUE THREAD

**Issue by moehle** [jump-dev/Convex.jl#437]
Hi!  I'm testing a new solver, which is failing a single test in the Problem Depot.  It's Convex.jl/src/problem_depot/problems/lp.jl:28, which tests the `abs` atom.  I've copied the code below:

 ```
    x = Variable(2,2)
    p = minimize(sum(abs(x)), x[2,2]>=1, x[1,1]>=1, x>=0; numeric_type = T)

    if test
        @test vexity(p) == ConvexVexity()
    end
    handle_problem!(p)
    if test
        @test p.optval ≈ 2 atol=atol rtol=rtol
        @test evaluate(sum(abs(x))) ≈ 2 atol=atol rtol=rtol
        @test p.constraints[1].dual ≈ 1 atol=atol rtol=rtol
        @test p.constraints[2].dual ≈ 1 atol=atol rtol=rtol
        @test p.constraints[3].dual[1,1] ≈ 0 atol=atol rtol=rtol
        @test p.constraints[3].dual[2,2] ≈ 0 atol=atol rtol=rtol
        @test p.constraints[3].dual[1,2] ≈ p.constraints[3].dual[2,1] atol=atol rtol=rtol
    end
```

The last test is the one I'm looking at.  It seems like `p.constraints[3].dual[1,2]` and `p.constraints[3].dual[2,1]` should each be between 0 and 1, but not necessarily equal.  (I guess it's strange for a solver to return two different numbers between 0 and 1, but it's mathematically correct.)

Am I missing something?

**Comment by ericphanson** [comment]
It's been awhile since I've thought about duals but I think that's right... At least, I don't see why they would need to be equal, but I think they do need to be at least `>= 0`; not sure about `<= 1`.

Looking at the KKT conditions, e.g. p. 224 of my go-to reference, [BV04](https://web.stanford.edu/~boyd/cvxbook/):
<img width="670" alt="Screenshot 2021-05-13 at 12 00 52" src="https://user-images.githubusercontent.com/5846501/118110587-e02da280-b3e2-11eb-9a1c-a201a215cec9.png">

We should have
```julia
λ= p.constraints[3].dual
λ[i,j] >= 0 # for all i, j
λ[i,j] * x[i,j] ==0 # for all i, j
```
and we know `x[1,1] == 1` and `x[2,2]` == 1, so we need the corresponding `λ`'s to be zero, but `x[1,2]` and `x[2,1]` are zero, so the corresponding lambdas can be anything `>=0`. There's one more KTT condition that touches those duals here, the last one. I think that gives us
```julia
gradient(f0, x) + λ[1,2] + λ[2,1] + 2 == 0
```
using `p.constraints[1].dual == 1` and `p.constraints[1].dual == 1`, and the derivatives of the constraint functions are just 1 (and there are no equality constraints, i.e. `h`s). So that leaves `gradient(f0, x)` which I didn't touch since Convex actually reformulates the `abs` and solves a different problem  (https://github.com/jump-dev/Convex.jl/blob/da206ee21374cb59d70ca3961a2283c71bfd425d/src/atoms/lp_cone/abs.jl#L46). But anyway, I think that's enough to see that the two values `λ[1,2]` and `λ[2,1]` don't need to be equal but have some constraint that they need to sum to a certain value.

So I think we could change that test to just check that those two values are each `>= 0`.

cc @ranocha

**Comment by moehle** [comment]
Ok great!  Thanks for taking a look.

The way I'm interpreting that last equation in BV04 is as a 2x2 set of equations:
```
[g11, g12]   [1, 0]        [0, 0]        [λ11, λ12]    [0, 0]   
[g21, g22] - [0, 0] * λ1 - [0, 1] * λ2 - [λ21, λ22]  = [0, 0]
```
Here `g11, g21, g12, g22` can be any subgradient of `abs` at `xstar = [1, 0; 0, 1]`, i.e., `g11 = g22 = 1`, and `g12` and `g21` can be anywhere between -1 and 1.  So `λ21` and `λ12` simply have to be between [-1 and 1].  (Of course they're nonnegative, so this really means between 0 and 1.)

From complementarity, we have also have `λ11 = λ22 = 0` and therefore `λ1 = λ2 = 1`.

**Comment by ericphanson** [comment]
Oops, I both messed up the signs and somehow scalarized it, thanks for writing it out properly. Let me just run through to be sure I understand: subgradient of absolute value at 0 is anything in [-1,1], and for x > 0, subgradient is 1 (since it's just the derivative). So that's the valuse of the g's, as you said. Then plugging in to the equation you wrote,
```
[1, g12]   [1, 0]        [0, 0]        [0, λ12]    [0, 0]   
[g21, 1] - [0, 0] * λ1 - [0, 1] * λ2 - [λ21, 0]  = [0, 0]
```
which gives us the `λ12=g12` and `λ21=g21` which gives us the restriction to [-1,1], and since they're non negative, that's [0,1]. Ok, makes sense to me!

Are you up for making a PR to change the tests?

---

I think the bit I'm unsure about is how reformulation affects these things, i.e. if Convex is actually solving a different problem that has the same optimal primal solution, do we end up with the same constraints on the dual values? Or maybe our extended formulations preseve the constraints on the dual values as well. (I'm OK with making this change without fully understanding that though, since I think it's at least more correct than what we have now.)

**Comment by moehle** [comment]
That's correct!  

Here's my hand-wavy argument for your second question.  It should be the case that "canonicalizing" preserves the optimal dual variables.  Consider the more general problem
```
minimize:  f0(x)
subject to:  fi(x) <= 0, for i = 1,...,n.
```
The dual variables are `λ1,..., λn`.  Convex.jl canonicalizes this to
```
minimize:  t
subject to:  f0(x) <= t, fi(x) <= 0, for i = 1,...,n.
```
There's an additional dual variable `λ0` here, but the KKT conditions imply `λ0=1` (the last condition, for the derivative with respect to `t`).  At which point, I believe the KKT conditions for the second problem reduce to the first.  Therefore the optimal primal-dual solution sets coincide.

I submitted a pull request!

**Comment by ericphanson** [comment]
Thanks for the PR! I'll release Convex v0.14.9 shortly with the fix.

Thanks for the sketch, I think that makes sense to me. I think the reformulation we do in this case is a bit more extensive in that we add another slack variable ([here](https://github.com/jump-dev/Convex.jl/blob/4068f80ec581ae77d8000d7f3fcb0387ce306577/src/atoms/second_order_cone/norm2.jl#L43)) and then add a second-order cone constraint on that variable, but probably most of these are kind of trivial and end up factoring out the same as in the case you sketched.
