### ISSUE TITLE
run convex with pajarito？(try to solve misdp with complex variable)

### ISSUE THREAD

**Issue by duyanran** [jump-dev/Convex.jl#438]
the related version of my packages are as follows:

```
`(v1.0) pkg> status`
 `   Status `C:\Users\duyanran\.julia\environments\v1.0\Project.toml`
`  [f65535da] Convex v0.14.8`
 ` [60bf3e95] GLPK v0.14.8`
`  [2e9cd046] Gurobi v0.8.1`
`  [6405355b] Mosek v1.1.3`
`  [1ec41992] MosekTools v0.9.4`
`  [2f354839] Pajarito v0.7.0`
`  [c946c3f1] SCS v0.7.1`
```
i wrote a code to illustrate my problem:
```
`b = randn(20)     # Sample measurement vector`
`tau= Convex.ComplexVariable()`
`t = Convex.ComplexVariable(20,20)`
`z = Convex.Variable(6, :Bin)`
`mod = minimize( sum(z) )    `
`mod.constraints += (sum(z) <= 1)`
`mod.constraints += (t[1,2] == 1+1im)`
`mod.constraints += [real(t) b ; b' tau] in :SDP`
`solve!(mod, micp_solver)`
`println("  selected features (z) = \n$(z.value)\n")`
`println("  selected features (z) = \n$(tau.value)\n")`
`println("  selected features (z) = \n$(t.value)\n")`
```
question is after i run my program is end up with this error:
```
`The provided `optimizer_constructor` is invalid. It must be callable with zero arguments. For example, "Ipopt.Optimizer" or "() -> ECOS.Optimizer()". It should not be an instantiated optimizer like "Ipopt.Optimizer()" or "ECOS.Optimizer()". (Note the difference in parentheses!)`
```

**does that means that i can not use pajarito to construct a composite solver ? or how can i change my code?**

i tried to degradation convex.jl with version 0.8.1
but here i got another problem, and i am trying to solve it by myself.

**Comment by ericphanson** [comment]
You can use Convex.jl version 0.12. Pajarito isn’t compatible with later versions of Convex since it does not support MathOptInterface (ref https://github.com/JuliaOpt/Pajarito.jl). Be wary of using earlier versions of Convex with complex numbers (I would use the latest version in the 0.12 series) because there were correctness bugs.

I used Convex 0.12 + Pajarito with complex numbers in some of the numerics for my thesis here, by the way: https://github.com/ericphanson/GuessworkQuantumSideInfo.jl

**Comment by duyanran** [comment]
thanks for your advise, you are right i tried convex 0.8.0 and it gives this:
`ERROR: LoadError: InexactError: Float64(-0.0 - 1.0im)`

and then i tried v0.12.7 and it worked !!!!!!
thank you so much!!!!!!!!!
you are the best!!!!!!!!

**Comment by duyanran** [comment]
Hi... another question is that i don't know how to let convex(v0.12.7) work with mosek(MosekTools v0.9.4, Mosek v1.1.3).

i tried 
`solver = Mosek.Optimizer`
and i got
`ERROR: LoadError: MethodError: no method matching solve!(::Problem, ::typeof(Mosek.Optimizer))`

i tried 
`solver = MosekSolver()`
but i got
` LoadError: UndefVarError: MosekSolver not defined`

but SCS always worked
emmm, kinda confused....

**Comment by odow** [comment]
The underlying issue is that Pajarito has not been updated to the latest version of Convex.jl.

 * You can use Pajarito + Convex.jl 0.12
 
 Mosek has been updated to the latest version of Convex.jl

 * You can use latest Mosek.jl + Convex.jl 0.14

There is no easy way to use Pajarito + Mosek + Convex.jl.

**Comment by ericphanson** [comment]
I think you can do it though, I did it in those experiments I linked. I think the version of Mosek you need is some obscure branch though, I will try to find it.

**Comment by ericphanson** [comment]
Try this:
```julia
using Pkg
Pkg.add([PackageSpec(name="Mosek", rev="b0.9"), PackageSpec(name="MosekTools"), PackageSpec(name="Convex", version = v"0.12.7"), PackageSpec(name="Pajarito"), PackageSpec(name="Cbc")])
using Convex, Mosek, Pajarito, MosekTools, Cbc

solver = PajaritoSolver(mip_solver=CbcSolver(), cont_solver=MosekSolver()) 
b = randn(20)     # Sample measurement vector
tau= Convex.ComplexVariable()
t = Convex.ComplexVariable(20,20)
z = Convex.Variable(6, :Bin)
mod = minimize( sum(z) )    
mod.constraints += (sum(z) <= 1)
mod.constraints += (t[1,2] == 1+1im)
mod.constraints += [real(t) b ; b' tau] in :SDP
solve!(mod, solver)
println("  selected features (z) = \n$(z.value)\n")
println("  selected features (z) = \n$(tau.value)\n")
println("  selected features (z) = \n$(t.value)\n")
```

I don't have a Mosek license anymore so for me it errors during the solving phase when it can't find a license, but it seems to work otherwise. But:
* It does not work on Julia 1.6, only on Julia 1 to 1.5
* It needs Mosek v8 (https://www.mosek.com/downloads/list/8/), not v9
* it needs that particular branch of Mosek.jl, `Mosek#b0.9`

**Comment by odow** [comment]
I guess this is what I meant by "no easy way."

**Comment by ericphanson** [comment]
Fair enough 🙂. As someone who has had a need to try to solve these problems though, one might be very willing to jump through a few hoops in order to get the versions to align... there isn’t a ton of code out there for complex mixed-integer SDPs or other conic problems, at least when I looked. (Maybe now that SCIP is more redistributable, [SCIP-SDP](http://www.opt.tu-darmstadt.de/scipsdp/) might be easier to get working...)

**Comment by odow** [comment]
> complex mixed-integer SDPs 

Yeah, it's not exactly a widely used problem class!

**Comment by duyanran** [comment]
Really love you guys and many thanks to you two !

i tried to run the code, something went wrong:
`Starting MIP-solver-driven algorithm`
`ERROR: LoadError: Solver does not support lazy callbacks`
i think this is something with Cbc instead of mosek

i saw some document like this:
[https://jump.dev/JuMP.jl/v0.12/callbacks.html](url)
and it said: 

> Currently, we support lazy constraints, user-provided cuts, and user-provided heuristics for the Gurobi, CPLEX, and GLPK solvers. We do not yet support any other class of callbacks, but they may be accessible by using the solver’s low-level interface.

well.... i dont really want so-called " call back ".... and i dont know if there's any way to shut it down or something...

then i tried gurobi, but seemly there still exist some version fitting problem.....

```
(@v1.0) pkg> build Gurobi
   Building Gurobi → `C:\Users\duyanran\.julia\packages\Gurobi\dlJep\deps\build.log`
┌ Error: Error building `Gurobi`: 
│ ERROR: LoadError: Unable to locate Gurobi installation. Note that this must be downloaded separately from gurobi.com
│ Stacktrace:
│  [1] error(::String) at .\error.jl:33
│  [2] top-level scope at C:\Users\duyanran\.julia\packages\Gurobi\dlJep\deps\build.jl:62
│  [3] include(::String) at .\client.jl:439
│  [4] top-level scope at none:5
│ in expression starting at C:\Users\duyanran\.julia\packages\Gurobi\dlJep\deps\build.jl:61
└ @ Pkg.Operations D:\buildbot\worker\package_win64\build\usr\share\julia\stdlib\v1.4\Pkg\src\Operations.jl:899
```
 well, i can well solve MISDP with SCS instead of Mosek so this problem don't really need to be solved, thanks for Eric's efforts ! 
if this could be fixed will be great but if it cost too much time, just ignore it ~

**Comment by ericphanson** [comment]
>i tried to run the code, something went wrong:
Starting MIP-solver-driven algorithm
ERROR: LoadError: Solver does not support lazy callbacks
i think this is something with Cbc instead of mosek

Ah I forgot about this, you also need `mip_solver_drives=false` to use Cbc with Pajarito:
```julia
solver = PajaritoSolver(mip_solver=CbcSolver(), cont_solver=MosekSolver(), mip_solver_drives=false) 
```

**Comment by duyanran** [comment]
got it !  THX !
