### ISSUE TITLE
Quesitons about how Convex.jl works

### ISSUE THREAD

**Issue by JinraeKim** [jump-dev/Convex.jl#472]
Hi, I'm interested in how Convex.jl works internally.

As I know, it converts a given problem to a conic problem and solves it via conic solvers.

I wonder if
1) the conic transformation is always taken
2) the conic transformation can be a bottleneck (i.e., much slower than solving time of the transformed conic problem)
3) what's the time complexity of famous conic solvers

**Comment by ericphanson** [comment]
Have you seen https://jump.dev/Convex.jl/stable/#Extended-formulations-and-the-DCP-ruleset by the way? That has some explanation.

1. yes, we currently always reformulate to use extended formulations
2. I think this can happen, yes. Convex is also not type stable internally so this might happen more than it should, due to the inefficiency there.
3. As far as I know, the way to find this is to look up the algorithm a solver is using and then look at info on that algorithm. Specific solvers will generally not have a different time complexity just different constant factors. If you don’t have any binary or integer variables, then DCP problems (ones where Convex does not emit a warning) should generally be solvable in polynomial time (ie time scaling as a polynomial in the # of inputs), if I remember correctly. However this usually relies on various assumptions about the values used as well, like they are bounded, or other numeric stability conditions.

**Comment by JinraeKim** [comment]
@ericphanson
It's really helpful, thank you so much!

**Comment by odow** [comment]
Closing because there doesn't seem to be anything actionable here.
