### ISSUE TITLE
Positive semidefinite constraint still gives small negative eigenvalues

### ISSUE THREAD

**Issue by biona001** [jump-dev/Convex.jl#490]
I'm trying to maximize an expression such that a matrix has to be positive semidefinite. However after solving the problem, this matrix contains "small negative eigenvalues" which later causes a Cholesky factorization to fail. What is the recommended way to proceed? 

**Problem:**
Given positive definite matrix `Σ`, I'm trying to solve the following for `s`
![Screen Shot 2022-04-02 at 12 04 58 PM](https://user-images.githubusercontent.com/16760873/161397683-3d613cf8-91e7-43f5-af1b-b420ed1e1285.png)

**MWE:**
```julia
# simulate data
Random.seed!(2022)
n = 100
p = 200
X = randn(n, p)
Σ = X' * X

# solve SDP
svar = Variable(p)
problem = maximize(sum(svar), svar > 0, 1 > svar, 2Σ - Diagonal(svar) in :SDP)
solve!(problem, () -> SCS.Optimizer(verbose=false))
s = evaluate(svar)
```
check eigenvalues (these should all be positive)
```
eigvals(2Σ - Diagonal(s))

200-element Vector{Float64}:
   -3.101080654347303e-7
   -2.7623081450926185e-7
   -2.587427317829892e-7
   -2.493995420297844e-7
   -2.1496835291359574e-7
   -1.9842051425436525e-7
   -1.9598456193770021e-7
   -1.8284763218961943e-7
   -1.7416223475439557e-7
   -1.675431633567717e-7
   -1.616486115403083e-7
   -1.5732361237570105e-7
   -1.4155375101535406e-7
    ⋮
  797.8478356105294
  823.6054459434325
  827.2668655598852
  855.1745483615014
  858.7955536401146
  886.6630755655351
  925.9583841555428
  953.2405208558397
  970.845836873802
 1008.4485569441961
 1041.7501602014472
 1089.7616764851266
```
Cholesky fails
```julia
cholesky(Symmetric(2Σ - Diagonal(s)))
PosDefException: matrix is not positive definite; Cholesky factorization failed.
```

**Comment by ericphanson** [comment]
I believe that's how a lot of solvers work: they allow small violations in the constraints. One thing you could do is instead of `2Σ - Diagonal(svar) in :SDP`, do `2Σ - Diagonal(svar) - eps*I(n) in :SDP` where eps is some small value and `I(p)` is the identity matrix (from the LinearAlgebra stdlib). Then the constraint isn't just that the matrix is SDP but strictly positive-definite with eigenvalues bounded below by `eps`. Then as long as `eps` is greater than the constraint violation tolerance allowed by the solver, you should get strictly positive eigenvalues. (Of course, this could make the problem infeasible, if there is no matrix satisfying this new constraint).

Another option is to "project" the solution you get back onto the cone of positive semi-definite matrices. One approach to that is in https://github.com/timholy/PositiveFactorizations.jl, I guess another one would be to use the eigendecomposition and replace the negative eigenvalues with zeros, and reconstitute the matrix. E.g. something like
```julia
function project_psd(mat)
    vals, vecs = eigen(mat)
    return vecs * Diagonal(max.(zero(eltype(vals)), vals)) * vecs'
end
```

**Comment by odow** [comment]
This is expected behavior by SCS. It works to numerical tolerances. Here are the docs for SCS: https://www.cvxgrp.org/scs/

You can try changing some of the settings: https://www.cvxgrp.org/scs/api/settings.html
```julia
solve!(
    problem,
    Convex.MOI.OptimizerWithAttributes(
        SCS.Optimizer,
        "eps_infeas" => 1e-9,
    ),
)
```

For a cholesky with small negative eigen values, see this example:
https://jump.dev/JuMP.jl/stable/tutorials/conic/max_cut_sdp/

**Comment by biona001** [comment]
Thank you both for the response. 

Doing `2Σ - Diagonal(svar) - 1e-6*I(p) in :SDP` actually increased the computation time from 6 seconds to >10 min, so maybe this isn't the best idea. I also tried
```julia
solve!(
    problem,
    Convex.MOI.OptimizerWithAttributes(
        () -> SCS.Optimizer(verbose=false),
        "eps_abs" => 1e-8
    ),
)
```
which gives me even smaller eigenvalues, but they are still negative (making `eps_abs` too small will also substantially increase compute time). 

What if I just compute `cholesky(Symmetric(2Σ - Diagonal(s))) + eps*I` with some small `eps`? Is that a bad idea? 

Otherwise, I think the best idea is to do the projection, i.e. computing eigendecomposition and replacing the negative eigenvalues by 0.

**Comment by biona001** [comment]
In either case, I think this issue can be closed. Thank you both for the fast response.
