### ISSUE TITLE
Add `backend(p::Problem, optimizer)` utility

### ISSUE THREAD

**Issue by ericphanson** [jump-dev/Convex.jl#557]
> One useful utility might be `backend(p::Problem, optimizer)` which returns the MOI model. Then people are free to do what they like with it.

_Originally posted by @odow in https://github.com/jump-dev/Convex.jl/issues/551#issuecomment-1888211729_

**Comment by odow** [comment]
I looked at this briefly. I don't know if it's super useful. It's not urgent

**Comment by odow** [comment]
I'm souring on this, mainly because if you have the MOI model, there's not much you can do without linking it to the variables. (And that's hard, because of shapes, complex variables, etc).

Experts can do `context = Convex.Context(p, optimizer_factory)` and then `context.model`, or they can look in `p.model` after a solve.

I don't know if we need `backend`.
